// Zero-dependency static site build: renders every page from src/data into dist/.
//   node build.mjs            — build once
//   SITE_URL=https://… node build.mjs   — override siteUrl from site.config.mjs (used by CI)

import { rmSync, mkdirSync, writeFileSync, readFileSync, readdirSync, cpSync, existsSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import config from './site.config.mjs';
import { securityHeaders } from './src/security.mjs';

if (process.env.SITE_URL) config.siteUrl = process.env.SITE_URL;
config.siteUrl = config.siteUrl.replace(/\/+$/, '');
// NOINDEX=1 marks a build as a non-production mirror (e.g. the GitHub Pages preview) so search engines skip it.
config.noindex = process.env.NOINDEX === '1';
// GA_MEASUREMENT_ID overrides the analytics ID for one build (used to test the consent banner).
if (process.env.GA_MEASUREMENT_ID) config.analytics.gaMeasurementId = process.env.GA_MEASUREMENT_ID;
// ACCOUNT_URL overrides where "Sign in" / "Create account" lead (e.g. http://localhost:4000 for local testing).
if (process.env.ACCOUNT_URL) config.links.account = process.env.ACCOUNT_URL;
config.links.account = config.links.account.replace(/\/+$/, '');

const { layout } = await import('./src/templates/layout.mjs');
const { default: home } = await import('./src/templates/home.mjs');
const { solutionsIndex, servicePage } = await import('./src/templates/solutions.mjs');
const { default: configure } = await import('./src/templates/configure.mjs');
const { partners, academy, coursePage, about, contact, requestStatus, privacy, terms, notFound, serverError } = await import('./src/templates/pages.mjs');
const { areas } = await import('./src/data/services.mjs');
const { courses, currency } = await import('./src/data/courses.mjs');
const emailTemplates = await import('./src/emails/templates.mjs');
const { questions } = await import('./src/data/questions.mjs');

const here = dirname(fileURLToPath(import.meta.url));
const src = join(here, 'src');
const dist = join(here, 'dist');

rmSync(dist, { recursive: true, force: true });
mkdirSync(join(dist, 'assets/css'), { recursive: true });

/* ---------- assets ---------- */

const cssFiles = ['base.css', 'components.css', 'sections.css', 'journeys.css', 'vignettes.css', 'configure.css'];
const css = cssFiles
  .map((f) => readFileSync(join(src, 'assets/css', f), 'utf8'))
  .join('\n')
  .replace(/\/\*[\s\S]*?\*\//g, '')
  .replace(/\n\s*\n/g, '\n')
  .replace(/^\s+/gm, '');

// One version string for every stylesheet and script, derived from their contents. It is appended
// to asset URLs (and to the scripts' own imports) so they can be cached for a year yet update at once.
const jsFiles = readdirSync(join(src, 'assets/js')).filter((f) => f.endsWith('.js')).sort();
const jsSources = Object.fromEntries(jsFiles.map((f) => [f, readFileSync(join(src, 'assets/js', f), 'utf8')]));
config.assetVersion = createHash('sha256').update(css).update(Object.values(jsSources).join('')).digest('hex').slice(0, 10);

writeFileSync(join(dist, 'assets/css/site.css'), css);
mkdirSync(join(dist, 'assets/js'), { recursive: true });
for (const [file, source] of Object.entries(jsSources)) {
  writeFileSync(join(dist, 'assets/js', file), source.replace(/(from\s+'\.\/[\w-]+\.js)'/g, `$1?v=${config.assetVersion}'`));
}
cpSync(join(src, 'assets/img'), join(dist, 'assets/img'), { recursive: true, filter: (p) => !p.endsWith('.json') });
const hasOg = existsSync(join(src, 'assets/img/og.jpg'));

/* ---------- payment API ---------- */

// The PHP endpoints are copied as they are; the price list they charge from is generated
// from src/data/courses.mjs so the server and the site can never disagree.
cpSync(join(src, 'api'), join(dist, 'api'), { recursive: true });
const php = (v) => `'${String(v).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
const catalog = courses
  .map((c) => `    ${php(c.slug)} => ['name' => ${php(c.name)}, 'price' => ${Number(c.price)}, 'coupons' => [${c.coupons.map((k) => `${php(k.code.toUpperCase())} => ${Number(k.finalPrice)}`).join(', ')}]],`)
  .join('\n');
writeFileSync(join(dist, 'api/catalog.php'), `<?php\n// Generated by build.mjs from src/data/courses.mjs — do not edit.\nreturn [\n  'currency' => ${php(currency)},\n  'courses' => [\n${catalog}\n  ],\n];\n`);

// Email templates, shared by the PHP API and its Node mirror.
// …together with the label of every question, so emails can name the answers they list.
const answerLabels = { ...Object.fromEntries(questions.map((q) => [q.id, q.label])), goal: 'Goal', engagement: 'Engagement model', services: 'Services' };
writeFileSync(join(dist, 'api/emails.json'), JSON.stringify({ row: emailTemplates.row, emails: emailTemplates.emails, labels: answerLabels }));

/* ---------- pages ---------- */

// path is the page's directory relative to the site root: '' | 'solutions/' | 'solutions/content/'
const pages = [
  ['', home],
  ['solutions/', solutionsIndex],
  ...areas.map((a) => [`solutions/${a.slug}/`, (ctx) => servicePage(ctx, a)]),
  ['configure/', configure],
  ['request-status/', requestStatus],
  ['partners/', partners],
  ['academy/', academy],
  ...courses.map((c) => [`academy/${c.slug}/`, (ctx) => coursePage(ctx, c)]),
  ['about/', about],
  ['contact/', contact],
  ['privacy/', privacy],
  ['terms/', terms],
];

for (const [path, render] of pages) {
  const root = '../'.repeat(path.split('/').filter(Boolean).length);
  const page = render({ root, path });
  const dir = join(dist, path);
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, 'index.html'), layout({ ...page, path, root, hasOg }));
}

// System pages can be served from any depth, so they need root-absolute asset URLs.
const basePath = config.siteUrl ? new URL(config.siteUrl + '/').pathname : '/';
writeFileSync(join(dist, '404.html'), layout({ ...notFound({ root: basePath }), path: '404.html', root: basePath, hasOg }));
writeFileSync(join(dist, '500.html'), layout({ ...serverError({ root: basePath }), path: '500.html', root: basePath, hasOg }));

/* ---------- crawl files ---------- */

if (config.siteUrl && !config.noindex) {
  const urls = pages.map(([p]) => `  <url><loc>${config.siteUrl}/${p}</loc></url>`).join('\n');
  writeFileSync(join(dist, 'sitemap.xml'), `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls}\n</urlset>\n`);
}
writeFileSync(join(dist, 'robots.txt'), config.noindex ? 'User-agent: *\nDisallow: /\n' : `User-agent: *\nAllow: /\n${config.siteUrl ? `Sitemap: ${config.siteUrl}/sitemap.xml\n` : ''}`);
writeFileSync(join(dist, '.nojekyll'), '');

// Apache / LiteSpeed configuration (ignored by GitHub Pages): error pages, HTTPS, one canonical host,
// security headers, compression and caching. Versioned assets are cached for a year; pages always revalidate.
writeFileSync(
  join(dist, '.htaccess'),
  `ErrorDocument 404 ${basePath}404.html
ErrorDocument 500 ${basePath}500.html
ErrorDocument 503 ${basePath}500.html
Options -Indexes

<IfModule mod_rewrite.c>
  RewriteEngine On
${config.siteUrl.startsWith('https://') ? `  RewriteCond %{HTTPS} !=on
  RewriteCond %{REQUEST_URI} !^/\\.well-known/
  RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
` : ''}  RewriteCond %{HTTP_HOST} ^www\\.(.+)$ [NC]
  RewriteRule ^ https://%1%{REQUEST_URI} [R=301,L]${config.links.account ? `
  # walnutdatatech.com/login (and /register, /account) open the Walnut account portal
  RewriteRule ^(login|register|account)/?$ ${config.links.account}/$1 [R=302,L]` : ''}
</IfModule>

<IfModule mod_headers.c>
${Object.entries(securityHeaders).map(([k, v]) => `  Header always set ${k} "${v}"`).join('\n')}
  Header always set Strict-Transport-Security "max-age=15552000" env=HTTPS
  <FilesMatch "\\.(css|js|svg|jpg|jpeg|png|webp|woff2)$">
    Header set Cache-Control "public, max-age=31536000, immutable"
  </FilesMatch>
  <FilesMatch "\\.(html|xml|txt)$">
    Header set Cache-Control "no-cache"
  </FilesMatch>
</IfModule>

<IfModule mod_deflate.c>
  AddOutputFilterByType DEFLATE text/html text/css text/javascript application/javascript application/json image/svg+xml application/xml text/plain
</IfModule>
`
);

console.log(`Built ${pages.length + 2} pages → dist/ (${(css.length / 1024).toFixed(1)} kB CSS)${config.siteUrl ? ` for ${config.siteUrl}` : ''}`);
