<?php
// Shared helpers for the payment API. Works on PHP 7.4+ with the curl extension.
declare(strict_types=1);

// Errors go to the server log, never to the visitor.
ini_set('display_errors', '0');

function respond(int $status, array $body): void
{
    http_response_code($status);
    header('Content-Type: application/json; charset=utf-8');
    header('Cache-Control: no-store');
    header('X-Content-Type-Options: nosniff');
    echo json_encode($body, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
    exit;
}

// Accepts only same-origin JSON POSTs and returns the decoded body.
function read_post(): array
{
    if (($_SERVER['REQUEST_METHOD'] ?? '') !== 'POST') {
        header('Allow: POST');
        respond(405, ['error' => 'Method not allowed.']);
    }
    $origin = $_SERVER['HTTP_ORIGIN'] ?? '';
    if ($origin !== '') {
        $host = strtolower((string) preg_replace('/:\d+$/', '', $_SERVER['HTTP_HOST'] ?? ''));
        if (strtolower((string) parse_url($origin, PHP_URL_HOST)) !== $host) {
            respond(403, ['error' => 'Cross-site requests are not allowed.']);
        }
    }
    // Browsers cannot send JSON cross-site without a preflight, so insisting on it blocks forged form posts.
    if (stripos($_SERVER['CONTENT_TYPE'] ?? '', 'application/json') !== 0) {
        respond(400, ['error' => 'Invalid request.']);
    }
    $raw = file_get_contents('php://input');
    if ($raw === false || strlen($raw) > 32768) {
        respond(400, ['error' => 'Invalid request.']);
    }
    $data = json_decode($raw, true);
    if (!is_array($data)) {
        respond(400, ['error' => 'Invalid request.']);
    }
    return $data;
}

// Allows $max calls per $window seconds from one visitor, so the endpoint cannot be used to flood
// the payment account with orders. State lives in the system temp directory.
function rate_limit(string $bucket, int $max, int $window): void
{
    // Behind a proxy every request shares one REMOTE_ADDR, so prefer the forwarded client address.
    $forwarded = trim(explode(',', $_SERVER['HTTP_X_FORWARDED_FOR'] ?? '')[0]);
    $client = $forwarded !== '' ? $forwarded : ($_SERVER['REMOTE_ADDR'] ?? 'unknown');
    $handle = @fopen(sys_get_temp_dir() . '/walnut-rl-' . hash('sha256', $bucket . '|' . $client), 'c+');
    if ($handle === false) {
        return; // never block a payment because the temp directory is unavailable
    }
    flock($handle, LOCK_EX);
    $now = time();
    $hits = array_values(array_filter(
        array_map('intval', explode("\n", (string) stream_get_contents($handle))),
        function ($time) use ($now, $window) {
            return $time > $now - $window;
        }
    ));
    $blocked = count($hits) >= $max;
    if (!$blocked) {
        $hits[] = $now;
        ftruncate($handle, 0);
        rewind($handle);
        fwrite($handle, implode("\n", $hits));
    }
    flock($handle, LOCK_UN);
    fclose($handle);
    if ($blocked) {
        header('Retry-After: ' . $window);
        respond(429, ['error' => 'Too many attempts. Please wait a few minutes and try again.']);
    }
}

// config.php is written by the deploy script and never committed. It holds the Razorpay keys
// and the Twilio email settings; either part may be missing.
function load_config(): array
{
    $file = __DIR__ . '/config.php';
    $config = is_file($file) ? require $file : null;
    return is_array($config) ? $config : [];
}

function require_payments(array $config): void
{
    if (empty($config['key_id']) || empty($config['key_secret'])) {
        respond(503, ['error' => 'Online payment is not set up yet. Please try again later.']);
    }
}

function email_configured(array $config): bool
{
    return !empty($config['twilio_key']) && !empty($config['twilio_secret'])
        && !empty($config['email_from']) && !empty($config['email_notify']);
}

// True the first time it is called for a key, false afterwards (state in the system temp directory).
// Used so a retried request does not send the same email twice.
function first_time(string $key): bool
{
    $file = sys_get_temp_dir() . '/walnut-once-' . hash('sha256', $key);
    if (is_file($file)) {
        return false;
    }
    @file_put_contents($file, (string) time());
    return true;
}

// {{name}} is HTML-escaped in the HTML part; {{{name}}} is inserted as given (already escaped by the caller).
function render_template(string $template, array $vars, array $raw, bool $html): string
{
    return (string) preg_replace_callback(
        '/\{\{\{(\w+)\}\}\}|\{\{(\w+)\}\}/',
        function ($m) use ($vars, $raw, $html) {
            if ($m[1] !== '') {
                return (string) ($raw[$m[1]] ?? '');
            }
            $value = (string) ($vars[$m[2]] ?? '');
            return $html ? htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8') : $value;
        },
        $template
    );
}

// emails.json is generated by the build: the email templates and the label of every question.
function email_templates(): ?array
{
    static $templates = false;
    if ($templates === false) {
        $templates = json_decode((string) @file_get_contents(__DIR__ . '/emails.json'), true);
    }
    return is_array($templates) ? $templates : null;
}

// The answers of a University request beyond the fixed fields: { questionId: text | [text, …] }.
// Keys are short and alphanumeric; values are cleaned and length-checked, never silently cut.
function read_answers($raw): array
{
    $answers = [];
    if (!is_array($raw)) {
        return $answers;
    }
    $refuse = function () {
        respond(422, ['error' => 'Some of the details could not be accepted. Please check them and try again.']);
    };
    $text = function ($value, int $max) use ($refuse): string {
        if (!is_string($value)) {
            $refuse();
        }
        $value = trim((string) preg_replace('/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]+/', ' ', $value));
        if (strlen($value) > $max) {
            $refuse();
        }
        return $value;
    };
    foreach ($raw as $key => $value) {
        if (!preg_match('/^[A-Za-z][A-Za-z0-9]{0,39}$/', (string) $key) || count($answers) >= 50) {
            $refuse();
        }
        if (is_array($value)) {
            if (count($value) > 50) {
                $refuse();
            }
            $value = array_values(array_filter(array_map(function ($item) use ($text) {
                return $text($item, 300);
            }, $value), 'strlen'));
        } else {
            $value = $text($value, 4000);
        }
        if ($value !== '' && $value !== []) {
            $answers[(string) $key] = $value;
        }
    }
    return $answers;
}

// A question's label for emails: the one from the question data, else the key spelt out.
function answer_label(string $key): string
{
    $labels = email_templates()['labels'] ?? [];
    return isset($labels[$key]) ? (string) $labels[$key] : ucfirst(strtolower((string) preg_replace('/(?<=[a-z0-9])(?=[A-Z])/', ' ', $key)));
}

// Sends one templated email through Twilio. $rows is a list of [label, value]; empty values are skipped.
// Returns false instead of failing the request: callers decide whether a failed email matters.
function send_email(array $config, string $template, string $toAddress, string $toName, array $vars, array $rows = []): bool
{
    $templates = email_templates();
    if (!is_array($templates) || !isset($templates['emails'][$template]) || !function_exists('curl_init') || !email_configured($config)) {
        error_log('Email "' . $template . '" was not sent: email is not set up on this server.');
        return false;
    }

    $rowsHtml = '';
    $rowsText = '';
    foreach ($rows as $row) {
        $value = (string) $row[1];
        if ($value === '') {
            continue;
        }
        $rowsHtml .= render_template($templates['row'], ['label' => $row[0]], ['value' => nl2br(htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'))], true);
        $rowsText .= $row[0] . ': ' . $value . "\n";
    }
    $parts = $templates['emails'][$template];
    $subject = trim((string) preg_replace('/[\x00-\x1F\x7F]+/', ' ', render_template($parts['subject'], $vars, [], false)));

    $ch = curl_init('https://comms.twilio.com/v1/Emails');
    curl_setopt_array($ch, [
        CURLOPT_POST => true,
        CURLOPT_USERPWD => $config['twilio_key'] . ':' . $config['twilio_secret'],
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_TIMEOUT => 20,
        CURLOPT_HTTPHEADER => ['Content-Type: application/json'],
        CURLOPT_POSTFIELDS => json_encode([
            'from' => ['address' => $config['email_from'], 'name' => $config['email_from_name'] ?? 'Walnut Data Tech'],
            'to' => [['address' => $toAddress, 'name' => $toName !== '' ? $toName : $toAddress]],
            'content' => [
                'subject' => $subject,
                'html' => render_template($parts['html'], $vars, ['rows' => $rowsHtml], true),
                'text' => render_template($parts['text'], $vars, ['rows' => $rowsText], false),
            ],
        ], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES),
    ]);
    curl_exec($ch);
    $status = (int) curl_getinfo($ch, CURLINFO_RESPONSE_CODE);
    if ($status < 200 || $status >= 300) {
        error_log('Email "' . $template . '" failed: Twilio responded HTTP ' . $status);
        return false;
    }
    return true;
}

function onboarding_configured(array $config): bool
{
    return !empty($config['onboarding_url']) && !empty($config['onboarding_key']);
}

// One JSON call to the Onboarding Tool, authenticated with the shared key.
// Returns [HTTP status (0 when it could not be reached), decoded reply or []].
function onboarding_post(array $config, string $path, array $payload): array
{
    $ch = curl_init(rtrim((string) $config['onboarding_url'], '/') . $path);
    curl_setopt_array($ch, [
        CURLOPT_POST => true,
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_CONNECTTIMEOUT => 5,
        CURLOPT_TIMEOUT => 10,
        CURLOPT_HTTPHEADER => ['Content-Type: application/json', 'X-Walnut-Key: ' . $config['onboarding_key']],
        CURLOPT_POSTFIELDS => json_encode($payload, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES),
    ]);
    $body = curl_exec($ch);
    $reply = is_string($body) ? json_decode($body, true) : null;
    return [(int) curl_getinfo($ch, CURLINFO_RESPONSE_CODE), is_array($reply) ? $reply : []];
}

// Files a University enquiry as a request in the Onboarding Tool, server to server — the key never
// reaches the browser. The tool only records a request; an admin approves it before any account exists.
// Returns ['reference' => 'UR-000123', 'duplicate' => bool] once the tool has stored the request, or null
// instead of failing: the team is told in its email, and the visitor's request still counts.
function forward_university_request(array $config, array $request): ?array
{
    if (!onboarding_configured($config) || !function_exists('curl_init')) {
        return null;
    }
    [$status, $reply] = onboarding_post($config, '/api/v1/public/university-requests', $request);
    if ($status < 200 || $status >= 300 || !is_string($reply['reference'] ?? null)) {
        error_log('University request was not filed: the Onboarding Tool responded HTTP ' . $status);
        return null;
    }
    // 201 = a new request; 200 = this email already had an open request, which was updated.
    return ['reference' => substr($reply['reference'], 0, 40), 'duplicate' => $status === 200];
}

// Calls the Razorpay REST API with the account's key pair.
// With $fatal false, a failure returns [] instead of ending the request.
function razorpay(string $method, string $path, ?array $payload, array $config, bool $fatal = true): array
{
    if (!function_exists('curl_init')) {
        if (!$fatal) {
            return [];
        }
        respond(500, ['error' => 'Payment service is unavailable.']);
    }
    $ch = curl_init('https://api.razorpay.com/v1' . $path);
    curl_setopt_array($ch, [
        CURLOPT_CUSTOMREQUEST => $method,
        CURLOPT_USERPWD => $config['key_id'] . ':' . $config['key_secret'],
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_TIMEOUT => 20,
        CURLOPT_HTTPHEADER => ['Content-Type: application/json'],
    ]);
    if ($payload !== null) {
        curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($payload));
    }
    $body = curl_exec($ch);
    $status = (int) curl_getinfo($ch, CURLINFO_RESPONSE_CODE);

    $data = is_string($body) ? json_decode($body, true) : null;
    if ($status < 200 || $status >= 300 || !is_array($data)) {
        error_log('Razorpay ' . $method . ' ' . $path . ' failed with HTTP ' . $status);
        if (!$fatal) {
            return [];
        }
        respond(502, ['error' => 'We could not reach the payment service. Please try again.']);
    }
    return $data;
}
